service: proj-api

frameworkVersion: '3'

package:
  individually: true
  include:
  - index.ts

provider:
  profile: LOCAL-USE-ONLY
  name: aws
  runtime: nodejs18.x

custom:
  serverless-offline:
    host: 0.0.0.0
    httpPort: 3034
    useChildProcesses: true
    reloadHandler: true
  esbuild:
    exclude: ['pg-native', 'superagent-proxy']

functions:
  user-create:
    handler: src/user/create/index.index
    timeout: 60
    environment:
      postgresHost:                     ${file(env/api-config.json):postgresHost}
      postgresPort:                     ${file(env/api-config.json):postgresPort}
      postgresDatabase:                 ${file(env/api-config.json):postgresDatabase}
      postgresUser:                     ${file(env/api-config.json):postgresUser}
      postgresPassword:                 ${file(env/api-config.json):postgresPassword}
    events:
      - http:
          path: users
          method: POST
          cors: true

  users-get-all:
    handler: src/user/get-all/index.index
    timeout: 60
    environment:
      postgresHost:                     ${file(env/api-config.json):postgresHost}
      postgresPort:                     ${file(env/api-config.json):postgresPort}
      postgresDatabase:                 ${file(env/api-config.json):postgresDatabase}
      postgresUser:                     ${file(env/api-config.json):postgresUser}
      postgresPassword:                 ${file(env/api-config.json):postgresPassword}
    events:
      - http:
          path: users
          method: GET
          cors: true

  user-get: 
    handler: src/user/get/index.index
    timeout: 60
    environment:
      postgresHost:                     ${file(env/api-config.json):postgresHost}
      postgresPort:                     ${file(env/api-config.json):postgresPort}
      postgresDatabase:                 ${file(env/api-config.json):postgresDatabase}
      postgresUser:                     ${file(env/api-config.json):postgresUser}
      postgresPassword:                 ${file(env/api-config.json):postgresPassword}
    events:
      - http:
          path: users/{userId}
          method: GET
          cors: true

  user-delete:
    handler: src/user/delete/index.index
    timeout: 60
    environment:
      postgresHost:                     ${file(env/api-config.json):postgresHost}
      postgresPort:                     ${file(env/api-config.json):postgresPort}
      postgresDatabase:                 ${file(env/api-config.json):postgresDatabase}
      postgresUser:                     ${file(env/api-config.json):postgresUser}
      postgresPassword:                 ${file(env/api-config.json):postgresPassword}
    events:
      - http:
          path: users/{userId}
          method: DELETE
          cors: true


  project-create:
    handler: src/project/create/index.index
    timeout: 60
    environment:
      postgresHost:                     ${file(env/api-config.json):postgresHost}
      postgresPort:                     ${file(env/api-config.json):postgresPort}
      postgresDatabase:                 ${file(env/api-config.json):postgresDatabase}
      postgresUser:                     ${file(env/api-config.json):postgresUser}
      postgresPassword:                 ${file(env/api-config.json):postgresPassword}
    events:
      - http:
          path: projects
          method: POST
          cors: true

  project-get:
    handler: src/project/get/index.index
    timeout: 60
    environment:
      postgresHost:                     ${file(env/api-config.json):postgresHost}
      postgresPort:                     ${file(env/api-config.json):postgresPort}
      postgresDatabase:                 ${file(env/api-config.json):postgresDatabase}
      postgresUser:                     ${file(env/api-config.json):postgresUser}
      postgresPassword:                 ${file(env/api-config.json):postgresPassword}
    events:
      - http:
          path: projects/{projId}
          method: GET
          cors: true

  project-get-all:
    handler: src/project/get-all/index.index
    timeout: 60
    environment:
      postgresHost:                     ${file(env/api-config.json):postgresHost}
      postgresPort:                     ${file(env/api-config.json):postgresPort}
      postgresDatabase:                 ${file(env/api-config.json):postgresDatabase}
      postgresUser:                     ${file(env/api-config.json):postgresUser}
      postgresPassword:                 ${file(env/api-config.json):postgresPassword}
    events:
      - http:
          path: projects
          method: GET
          cors: true

  project-delete:
    handler: src/project/delete/index.index
    timeout: 60
    environment:
      postgresHost:                     ${file(env/api-config.json):postgresHost}
      postgresPort:                     ${file(env/api-config.json):postgresPort}
      postgresDatabase:                 ${file(env/api-config.json):postgresDatabase}
      postgresUser:                     ${file(env/api-config.json):postgresUser}
      postgresPassword:                 ${file(env/api-config.json):postgresPassword}
    events:
      - http:
          path: projects/{projId}
          method: DELETE
          cors: true


  ticket-create:
    handler: src/ticket/create/index.index
    timeout: 60
    environment:
      postgresHost:                     ${file(env/api-config.json):postgresHost}
      postgresPort:                     ${file(env/api-config.json):postgresPort}
      postgresDatabase:                 ${file(env/api-config.json):postgresDatabase}
      postgresUser:                     ${file(env/api-config.json):postgresUser}
      postgresPassword:                 ${file(env/api-config.json):postgresPassword}
    events:
      - http:
          path: tickets
          method: POST
          cors: true

  ticket-get:
    handler: src/ticket/get/index.index
    timeout: 60
    environment:
      postgresHost:                     ${file(env/api-config.json):postgresHost}
      postgresPort:                     ${file(env/api-config.json):postgresPort}
      postgresDatabase:                 ${file(env/api-config.json):postgresDatabase}
      postgresUser:                     ${file(env/api-config.json):postgresUser}
      postgresPassword:                 ${file(env/api-config.json):postgresPassword}
    events:
      - http:
          path: ticket/{ticketId}
          method: GET
          cors: true

  ticket-get-all:
    handler: src/ticket/get-all/index.index
    timeout: 60
    environment:
      postgresHost:                     ${file(env/api-config.json):postgresHost}
      postgresPort:                     ${file(env/api-config.json):postgresPort}
      postgresDatabase:                 ${file(env/api-config.json):postgresDatabase}
      postgresUser:                     ${file(env/api-config.json):postgresUser}
      postgresPassword:                 ${file(env/api-config.json):postgresPassword}
    events:
      - http:
          path: tickets/{projId}
          method: GET
          cors: true

  ticket-delete:
    handler: src/ticket/delete/index.index
    timeout: 60
    environment:
      postgresHost:                     ${file(env/api-config.json):postgresHost}
      postgresPort:                     ${file(env/api-config.json):postgresPort}
      postgresDatabase:                 ${file(env/api-config.json):postgresDatabase}
      postgresUser:                     ${file(env/api-config.json):postgresUser}
      postgresPassword:                 ${file(env/api-config.json):postgresPassword}
    events:
      - http:
          path: tickets/{ticketId}
          method: DELETE
          cors: true

  ticket-update:
    handler: src/ticket/update/index.index
    timeout: 60
    environment:
      postgresHost:                     ${file(env/api-config.json):postgresHost}
      postgresPort:                     ${file(env/api-config.json):postgresPort}
      postgresDatabase:                 ${file(env/api-config.json):postgresDatabase}
      postgresUser:                     ${file(env/api-config.json):postgresUser}
      postgresPassword:                 ${file(env/api-config.json):postgresPassword}
    events:
      - http:
          path: tickets/{ticketId}
          method: PUT
          cors: true


  comment-create:
    handler: src/comment/create/index.index
    timeout: 60
    environment:
      postgresHost:                     ${file(env/api-config.json):postgresHost}
      postgresPort:                     ${file(env/api-config.json):postgresPort}
      postgresDatabase:                 ${file(env/api-config.json):postgresDatabase}
      postgresUser:                     ${file(env/api-config.json):postgresUser}
      postgresPassword:                 ${file(env/api-config.json):postgresPassword}
    events:
      - http:
          path: comment
          method: POST
          cors: true

plugins:
  - serverless-esbuild
  - serverless-offline
