version: "3.8"
services:
  db:
    container_name: ticket_master_db
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./postgres/postgres.conf:/usr/local/etc/postgres/postgres.conf
    command: postgres -c config_file=/usr/local/etc/postgres/postgres.conf
    expose:
      - '5432'
    ports:
      - '5432:5432'
  ticket-master-api:
    container_name: api
    build: ./packages/proj-api
    ports:
      - '3034:3034'
    depends_on:
      - 'db'
      
    